sudo: required

services:
  - docker

before_install:
  - docker build -t facevedom/over-the-wire .

script:
  - docker run facevedom/over-the-wire

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push facevedom/over-the-wire